#!/bin/bash

# 📋 Task Manager v3.0 - Quick Command Reference
# Salva come QUICKREF.sh per accesso veloce

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  📋 Task Manager v3.0 - Quick Reference                   ║"
echo "║  Master-Slave Task Management System                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "🚀 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Avvia il server:"
echo "   cd task-manager-app && npm start"
echo ""
echo "2. Apri nel browser:"
echo "   http://localhost:5000"
echo ""
echo "3. Login Master:"
echo "   Username: master"
echo "   Password: masterpass"
echo ""

echo "🧪 TEST AUTOMATICO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Esegui tutti i 10 test:"
echo "   ./TEST_V3.sh"
echo ""

echo "🔌 API ENDPOINTS (cURL examples)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  LOGIN MASTER"
echo "   curl -X POST http://localhost:5000/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"master\",\"password\":\"masterpass\"}'"
echo ""

echo "2️⃣  CREA OPERATORE"
echo "   curl -X POST http://localhost:5000/api/auth/create-operator \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Authorization: Bearer \$TOKEN' \\"
echo "     -d '{\"username\":\"mario\",\"password\":\"mario123\"}'"
echo ""

echo "3️⃣  LISTA OPERATORI"
echo "   curl -X GET http://localhost:5000/api/auth/operators \\"
echo "     -H 'Authorization: Bearer \$TOKEN'"
echo ""

echo "4️⃣  CREA TASK"
echo "   curl -X POST http://localhost:5000/api/tasks \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Authorization: Bearer \$TOKEN' \\"
echo "     -d '{\"title\":\"Task\",\"assignedOperatorId\":2,\"priority\":\"HIGH\"}'"
echo ""

echo "5️⃣  ACCETTA TASK"
echo "   curl -X POST http://localhost:5000/api/tasks/1/accept \\"
echo "     -H 'Authorization: Bearer \$OP_TOKEN'"
echo ""

echo "6️⃣  PAUSA TASK"
echo "   curl -X POST http://localhost:5000/api/tasks/1/pause \\"
echo "     -H 'Authorization: Bearer \$OP_TOKEN'"
echo ""

echo "7️⃣  RIPRENDI TASK"
echo "   curl -X POST http://localhost:5000/api/tasks/1/resume \\"
echo "     -H 'Authorization: Bearer \$OP_TOKEN'"
echo ""

echo "8️⃣  COMPLETA TASK"
echo "   curl -X POST http://localhost:5000/api/tasks/1/notes \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Authorization: Bearer \$OP_TOKEN' \\"
echo "     -d '{\"note\":\"Done\",\"actualMinutes\":30,\"markCompleted\":true}'"
echo ""

echo "🗄️  DATABASE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Database location:"
echo "   server/prisma/data/tasks.db"
echo ""
echo "Reset database:"
echo "   rm -f server/prisma/data/tasks.db*"
echo "   DATABASE_URL='file:./prisma/data/tasks.db' npx prisma db push"
echo "   DATABASE_URL='file:./prisma/data/tasks.db' npx ts-node server/prisma/seed.ts"
echo ""

echo "📚 DOCUMENTAZIONE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 README_V3.md"
echo "   Full documentation, API docs, troubleshooting"
echo ""
echo "📄 FEATURES_COMPLETED.md"
echo "   Dettagli feature, schema DB, flussi utente"
echo ""
echo "📄 IMPLEMENTATION_SUMMARY.md"
echo "   Checklist implementazione, risultati test"
echo ""

echo "⚙️  TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Porta 5000 già in uso:"
echo "   lsof -i :5000 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo ""
echo "❌ Build con errori:"
echo "   npm run build"
echo ""
echo "❌ Browser non aggiorna:"
echo "   Ctrl+F5 (hard refresh)"
echo ""
echo "❌ JWT token scaduto:"
echo "   Fai login di nuovo (expiry: 8 ore)"
echo ""

echo "👤 CREDENZIALI DI TEST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Master:"
echo "   Username: master"
echo "   Password: masterpass"
echo ""
echo "Operatori (pre-creati):"
echo "   Username: operatore1"
echo "   Password: operatorpass"
echo ""
echo "Crea nuovo operatore da Master:"
echo "   Dashboard → Crea Nuovo Operatore"
echo ""

echo "🎯 WORKFLOW OPERATORE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Login come operatore"
echo "2. Vedi task assegnati"
echo "3. Clicca 'Accetta' → acceptedAt registrato"
echo "4. Lavora sul task"
echo "5. Opzione A: Clicca 'Completa' → completedAt registrato"
echo "6. Opzione B: Clicca 'Pausa' → pausedAt registrato"
echo "   Poi accetta un altro task"
echo "7. Clicca 'Riprendi' per continuare task pausato"
echo ""

echo "📊 FEATURE IMPLEMENTATE v3.0"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Master crea operatori nel database"
echo "✅ Rimozione sistema promozione operatori"
echo "✅ Tempo di accettazione task (acceptedAt)"
echo "✅ Un solo task attivo per operatore"
echo "✅ Pausa task per accettare altri"
echo "✅ Ripresa task messo in pausa"
echo "✅ Tempo automatico chiusura (completedAt)"
echo "✅ Backend API completa"
echo "✅ Frontend UI aggiornato"
echo "✅ Test automatici 10/10"
echo ""

echo "✅ SISTEMA PRONTO PER PRODUZIONE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
